// Package providerwirev4 contains the executable ProviderWire V4 HTTP contract.
//
// The checked-in OpenAPI document, JSON Schemas, test corpora, and response
// projections are curated. The pinned request capture is regenerated by the
// explicit update task documented in test/interop/providerwire-v4/INDEX.yaml.
// Handler provides the strict unary POST /language-model runtime, including
// validation, host policy, provider adaptation, bounded responses, and total
// timeout enforcement. Streaming, a Go client, and public wire data types are
// intentionally not provided.
//
// The active tolerant unary and streaming transport remains in the parent
// providerwire package.
package providerwirev4
