// Package providerwirev4 contains the executable ProviderWire V4 HTTP contract.
//
// The checked-in OpenAPI document, JSON Schemas, test corpora, and response
// projections are curated. The pinned request capture is regenerated by the
// explicit update task documented in test/interop/providerwire-v4/INDEX.yaml.
// This package is contract-only: it does not provide a decoder, handler, client, model adapter,
// host policy, stream server, or public wire data types.
//
// The active tolerant transport remains in the parent providerwire package.
package providerwirev4
