**

!go.gateway.work
!go.gateway.work.sum
!go.mod
!go.sum
!LICENSE
!NOTICE
!*.go

!ai-gateway/go.mod
!ai-gateway/go.sum
!ai-gateway/LICENSE
!ai-gateway/NOTICE
!ai-gateway/**/*.go
!ai-gateway/providerwire/v4/schema/request.json

!provider/**/*.go
!fallback/**/*.go
!output/**/*.go
!registry/**/*.go
!schema/**/*.go
!internal/**/*.go

!middleware/**/go.mod
!middleware/**/go.sum
!middleware/**/*.go
!providers/**/go.mod
!providers/**/go.sum
!providers/**/*.go
!providers/bedrock/provider_tool_schemas.json

**/*_test.go
